config-version: 1

# The root folder for the database change scripts
#root-folder: '/path/to/folder'

# The modules folder for jinja macros and templates to be used across multiple scripts.
#modules-folder: null

# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
#snowflake-account: 'xy12345.east-us-2.azure'

# The name of the snowflake user
#snowflake-user: 'user'

# The name of the default role to use. Can be overrideen in the change scripts.
#snowflake-role: 'role'

# The name of the default warehouse to use. Can be overridden in the change scripts.
#snowflake-warehouse: 'warehouse'

# The name of the default database to use. Can be overridden in the change scripts.
snowflake-database: 'CICD_DEV'

# Used to override the default name of the change history table (the default is METADATA.SCHEMACHANGE.CHANGE_HISTORY)
#change-history-table: null

# Define values for the variables to replaced in change scripts
#vars:
#  var1: 'value1'
#  var2: 'value2'
  #secrets:
 #   var3: 'value3' # This is considered a secret and will not be displayed in any output

# Create the change history schema and table, if they do not exist (the default is False)
#create-change-history-table: false

# Enable autocommit feature for DML commands (the default is False)
#autocommit: false

# Display verbose debugging details during execution (the default is False)
#verbose: false

# Run schemachange in dry run mode (the default is False)
#dry-run: false

# A string to include in the QUERY_TAG that is attached to every SQL statement executed
#query-tag: 'QUERY_TAG' 